import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'title': 'Bangladesh: Echoes of Bengal\'s Triumph and Tomorrow\'s Promise',
      'about': 'Bangladesh, a country nestled in South Asia, is a land of contrasts, rich history, and a promising future. Despite its relatively small size, this densely populated nation has made significant strides in various aspects of its development. From its vibrant culture to its economic resilience, Bangladesh stands as a testament to the indomitable spirit of its people. \n\n Situated between India to the west, north, and east, and Myanmar to the southeast, Bangladesh boasts a diverse geography that includes the fertile plains of the Ganges-Brahmaputra delta and the lush hills of the Chittagong Hill Tracts. With a population exceeding 160 million, Bangladesh is one of the most densely populated countries globally, and its people are known for their warmth, hospitality, and cultural diversity. \n\n The history of Bangladesh is a tapestry woven with threads of ancient civilizations, colonial influences, and the struggle for independence. The region has been home to various empires, including the Maurya and Gupta dynasties, and later, the Bengal Sultanate. The arrival of European powers, such as the British and the Portuguese, left a lasting imprint on the culture and society. \n\n The Bangladeshi people\'s resilience was particularly evident during the struggle for independence in 1971 when the nation separated from Pakistan. The Liberation War resulted in significant sacrifices and shaped the national identity, emphasizing the importance of linguistic and cultural heritage. \n\n Cultural diversity is a hallmark of Bangladesh, with a rich tapestry of literature, music, dance, and art. The country has produced globally acclaimed authors like Rabindranath Tagore, who won the Nobel Prize in Literature in 1913, and the filmmaker Satyajit Ray, whose work has left an indelible mark on world cinema.',
    },

    'bn_BD': {
      'title': 'বাংলাদেশ: বাংলার বিজয় এবং আগামীকালের প্রতিশ্রুতির প্রতিধ্বনি',
      'about': 'বাংলাদেশ, দক্ষিণ এশিয়ায় অবস্থিত একটি দেশ, বৈপরীত্যের দেশ, সমৃদ্ধ ইতিহাস এবং একটি প্রতিশ্রুতিশীল ভবিষ্যত। তুলনামূলকভাবে ছোট আকারের সত্ত্বেও, এই ঘনবসতিপূর্ণ জাতি তার উন্নয়নের বিভিন্ন দিকগুলিতে উল্লেখযোগ্য অগ্রগতি করেছে। তার প্রাণবন্ত সংস্কৃতি থেকে তার অর্থনৈতিক স্থিতিস্থাপকতা পর্যন্ত, বাংলাদেশ তার জনগণের অদম্য চেতনার প্রমাণ হিসাবে দাঁড়িয়ে আছে। \n\n পশ্চিমে, উত্তরে এবং পূর্বে ভারত এবং দক্ষিণ-পূর্বে মায়ানমারের মধ্যে অবস্থিত, বাংলাদেশ একটি বৈচিত্র্যময় ভূগোল নিয়ে গর্ব করে যার মধ্যে রয়েছে গঙ্গা-ব্রহ্মপুত্র ব-দ্বীপের উর্বর সমভূমি এবং পার্বত্য চট্টগ্রামের রসালো পাহাড়। 160 মিলিয়নের বেশি জনসংখ্যার সাথে, বাংলাদেশ বিশ্বব্যাপী সবচেয়ে ঘনবসতিপূর্ণ দেশগুলির মধ্যে একটি এবং এর জনগণ তাদের উষ্ণতা, আতিথেয়তা এবং সাংস্কৃতিক বৈচিত্র্যের জন্য পরিচিত। \n\n বাংলাদেশের ইতিহাস প্রাচীন সভ্যতা, ঔপনিবেশিক প্রভাব এবং স্বাধীনতার সংগ্রামের সুতোয় বোনা একটি ট্যাপেস্ট্রি। এই অঞ্চলটি মৌর্য ও গুপ্ত রাজবংশ এবং পরবর্তীকালে বঙ্গীয় সালতানাত সহ বিভিন্ন সাম্রাজ্যের আবাসস্থল। ব্রিটিশ এবং পর্তুগিজদের মতো ইউরোপীয় শক্তির আগমন সংস্কৃতি ও সমাজে স্থায়ী ছাপ ফেলে। \n\nবাংলাদেশের জনগণের স্থিতিস্থাপকতা বিশেষভাবে 1971 সালে স্বাধীনতা সংগ্রামের সময় স্পষ্টভাবে দেখা যায় যখন জাতি পাকিস্তান থেকে বিচ্ছিন্ন হয়। মুক্তিযুদ্ধের ফলে উল্লেখযোগ্য ত্যাগ স্বীকার হয় এবং ভাষাগত ও সাংস্কৃতিক ঐতিহ্যের গুরুত্বের উপর জোর দিয়ে জাতীয় পরিচয় গঠন করে। \n\n সাহিত্য, সঙ্গীত, নৃত্য এবং শিল্পের সমৃদ্ধ টেপেস্ট্রি সহ সাংস্কৃতিক বৈচিত্র্য বাংলাদেশের একটি বৈশিষ্ট্য। দেশটি রবীন্দ্রনাথ ঠাকুরের মতো বিশ্বব্যাপী প্রশংসিত লেখক তৈরি করেছে, যিনি 1913 সালে সাহিত্যে নোবেল পুরস্কার জিতেছিলেন এবং চলচ্চিত্র নির্মাতা সত্যজিৎ রায়, যার কাজ বিশ্ব চলচ্চিত্রে একটি অমোঘ চিহ্ন রেখে গেছে।',
    }


  };

}